SolutionBase/SolutionBase/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('auth/obtain_token', obtain_jwt_token),
    path('auth/refresh_token', refresh_jwt_token),
    path('accounts/', include('accounts.urls')),
    path('timesheets/', include('timesheets.urls')),
    path('api/timesheet/', include('timesheets.api.timesheet.urls')),
    path('api/activity/', include('timesheets.api.activity.urls')),
    path('api/project/', include('projects.api.urls')),
]

SolutionBase/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login',
         auth_views.LoginView.as_view(template_name='registration/login.html'),
         name='login'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('logged_in', views.LoggedIn.as_view(), name='logged_in'),
    path('logout', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

SolutionBase/timesheets/urls.py
from django.urls import path
from .views import TimesheetsBaseView

app_name = 'timesheets'

urlpatterns = [
    path('', TimesheetsBaseView.as_view(),
         name='base'),
]

SolutionBase/templates/base.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- Bootstrap 3 -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous">
        
        <!-- Optional theme -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous">
        
        <!-- Latest compiled and minified JavaScript -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- END_bootstrap 3 -->
</head>
<body>
    <div id="app">
        <!-- navigationbar -->
        <!-- NAVBAR -->
        <nav class="navbar mynav" role='navigation' id='navbar'>
            <div class="container">
                <a class='navbar-brand mynav' href="{% url 'home' %}">HOME</a>
        
                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}
                    <!-- is the user auth ? -->
                    <li>
                        <a href="{% url 'timesheets:base' %}">Timesheets</a>
                    </li> 
                    
                        {% if user.is_superuser %}
                        <!-- the user is a super type -->
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endif %}
        
                    <li>
                        <a href="{% url 'accounts:logout' %}">log Out</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
        
                    {% endif %}
                </ul>
            </div>
        </nav>
        <!-- END_NAVBAR -->

        <!-- Content -->
        <div class="container mycontent">
            {% block content %} 
            {% endblock %}
        </div>
        
    </div>
    <!-- END vue app -->

    {% if env == 'production' %}
        {% render_bundle 'manifest' %}
        {% render_bundle 'vendor' %}
    {% endif %}
    
    {% render_bundle 'app' %}
</body>
</html>

SolutionBase/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1> Welcome to the demo SolutionBase application</h1>

{% endblock %}